### ISSUE TITLE
Can't change the font size of the tickets

### ISSUE THREAD

**Issue by pagan11460** [eventespresso/eea-beaver-builder#21]
Hello, I just downloaded this plugin to use with Event Espresso and Beaver Builder. The Typography section of the Event Module should allow me to change the font size in the Tickets section. But no matter what I enter for a font size, the font-size doesn't change. So then I tried to fix it via CSS. The ticket size in the CSS is 8px with "! important" after it. However, when I change it to 16px, it appears to change while I'm still using Beaver Builder's Page Builder, but as soon as I publish BB and refresh my page, the fonts show up small - at - I guess - 8px. My client needs to launch this golf tournament this weekend. Can anyone help me (rather quickly)? Thanks so very much in advance.
<img width="988" alt="Screenshot 2019-05-17 15 52 50" src="https://user-images.githubusercontent.com/13998962/57952814-4c40a300-78bc-11e9-94bc-afaecc78a5fa.png">
<img width="1083" alt="Screenshot 2019-05-17 15 53 05" src="https://user-images.githubusercontent.com/13998962/57952815-4c40a300-78bc-11e9-9458-fab4d12b1565.png">

**Comment by mnelson4** [comment]
hi @pagan11460 can you provide a link to the event?

**Comment by pagan11460** [comment]
Hi mnelson... yes! Thank you. https://www.apkcharities.org/espresso-events/cpt-drew-ross-fallen-but-not-forgotten-memorial-golf-tournament/

**Comment by pagan11460** [comment]
I'm having other problems with the plugin, too. I need to write to support at Event Espresso. But this issue with the fonts is an issue with the eea-beaver-builder plugin.

**Comment by pagan11460** [comment]
Oh! I just saw your bio. Did you develop Event Espresso?

**Comment by mnelson4** [comment]
FYI the CSS that's making that text so small is coming from `https://www.apkcharities.org/?custom-css=7467549e68`:

Here is the CSS that's affecting it

```
table th, table td {
    padding: 8px;
    line-height: 18px;
    text-align: left;
    vertical-align: top;
    border-top: 1px solid #ddd;
    font-size: 8px !important;
}
```

that's making the text only 8px, then there's the next line that's making it 10xp:

```
/*WooC size of font in checkout*/
TABLE TH, TABLE TD
{
	padding: 8px;
	line-height: 18px;
	text-align: left;
	vertical-align: top;
	border-top: 1px solid #DDD;
	font-size: 10px !important;
}
/*end*/
```

Although I suspect you had those styles for some other reason. Hopefully you can add a more specific CSS selector for those styles.

I hope that helps. So it turns out, I don't think this is a bug in Event Espresso or Beaver Builder.

> I'm having other problems with the plugin, too. I need to write to support at Event Espresso. But this issue with the fonts is an issue with the eea-beaver-builder plugin.

We'll see if we can help with those too!

> Did you develop Event Espresso?

I'm one of the developers of Event Espresso, yes, but certainly not the only one!

Best wishes with your launch!
